/**
 * models/Session.js
 * Schema for a full chat session (groups many Chat messages together)
 */

const mongoose = require('mongoose');

const SessionSchema = new mongoose.Schema(
  {
    // Unique session ID (generated by frontend using uuid)
    sessionId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    // Optional: user's display name or 'Anonymous'
    userName: {
      type: String,
      default: 'Anonymous',
      trim: true,
      maxlength: 100,
    },

    // Optional link to a logged-in User account. Null = anonymous guest session.
    // Indexed so "give me all sessions for this user" (history/me) is fast.
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
      index: true,
    },

    // Reserved for future multi-language support — LexBot is English-only for now.
    language: {
      type: String,
      enum: ['en'],
      default: 'en',
    },

    // Total messages exchanged in this session
    messageCount: {
      type: Number,
      default: 0,
    },

    // Topics discussed in this session
    topicsDiscussed: {
      type: [String],
      default: [],
    },

    // Is session still active?
    isActive: {
      type: Boolean,
      default: true,
    },

    // When session was last used
    lastActiveAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    timestamps: true,
  }
);

// Auto-update lastActiveAt before every save
SessionSchema.pre('save', function (next) {
  this.lastActiveAt = Date.now();
  next();
});

module.exports = mongoose.model('Session', SessionSchema);